import json, sys, tempfile, unittest
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import render as r

STDIO = {"db": {"type": "stdio", "command": "npx", "args": ["-y", "x@1"],
                "env": {"POSTGRES_CONNECTION_STRING": "${DATABASE_URL:-postgres://localhost:5432/p}",
                        "PGAPPNAME": "agent"}}}
FWD = {"gh": {"type": "stdio", "command": "npx", "args": ["-y", "gh"],
              "env": {"GITHUB_PERSONAL_ACCESS_TOKEN": "${GITHUB_PERSONAL_ACCESS_TOKEN}"}}}
HTTP = {"api": {"type": "http", "url": "https://e.x/mcp",
                "headers": {"Authorization": "Bearer ${API_TOKEN}"}}}


class EnvRef(unittest.TestCase):
    def test_forms(self):
        self.assertEqual(r.env_ref("${A}"), ("A", None))
        self.assertEqual(r.env_ref("${A:-d}"), ("A", "d"))
        self.assertIsNone(r.env_ref("plain"))
        self.assertIsNone(r.env_ref("x ${A}"))


class Codex(unittest.TestCase):
    def test_forwarded_var(self):
        t = r.render_codex(FWD)
        self.assertIn('[mcp_servers.gh]\ncommand = "npx"\nargs = ["-y", "gh"]\nenv_vars = ["GITHUB_PERSONAL_ACCESS_TOKEN"]', t)
        self.assertTrue(t.startswith("# generated by agent-baseline"))
        self.assertTrue(t.endswith("[features]\nhooks = true\n"))

    def test_default_when_key_differs(self):
        t = r.render_codex(STDIO)
        self.assertIn('[mcp_servers.db.env]\nPOSTGRES_CONNECTION_STRING = "postgres://localhost:5432/p"\nPGAPPNAME = "agent"', t)
        self.assertNotIn("env_vars", t)

    def test_key_differs_without_default_is_error(self):
        bad = {"db": {"type": "stdio", "command": "x", "env": {"PGURL": "${DATABASE_URL}"}}}
        with self.assertRaisesRegex(r.RenderError, "db: env PGURL"):
            r.render_codex(bad)

    def test_bearer(self):
        self.assertIn('[mcp_servers.api]\nurl = "https://e.x/mcp"\nbearer_token_env_var = "API_TOKEN"', r.render_codex(HTTP))

    def test_other_header_is_error(self):
        bad = {"api": {"type": "http", "url": "u", "headers": {"X-Key": "${K}"}}}
        with self.assertRaisesRegex(r.RenderError, "api: header 'X-Key'"):
            r.render_codex(bad)

    def test_quoted_key(self):
        self.assertIn('[mcp_servers."a.b"]', r.render_codex({"a.b": {"type": "http", "url": "u"}}))


class OpenCode(unittest.TestCase):
    def test_shapes(self):
        o = json.loads(r.render_opencode({**STDIO, **HTTP}))
        self.assertEqual(o["$schema"], "https://opencode.ai/config.json")
        self.assertEqual(o["mcp"]["db"], {"type": "local", "command": ["npx", "-y", "x@1"], "enabled": True,
                                          "environment": {"POSTGRES_CONNECTION_STRING": "{env:DATABASE_URL}", "PGAPPNAME": "agent"}})
        self.assertEqual(o["mcp"]["api"], {"type": "remote", "url": "https://e.x/mcp", "enabled": True,
                                           "headers": {"Authorization": "Bearer {env:API_TOKEN}"}})


class Settings(unittest.TestCase):
    def test_merge_preserves_foreign_keys(self):
        with tempfile.TemporaryDirectory() as d:
            p = Path(d) / "settings.json"
            p.write_text(json.dumps({"permissions": {"allow": ["Bash(ls)"]}, "enabledPlugins": {"old@x": True}}))
            r.merge_settings(p, ["b", "a"], ["p@x"])
            s = json.loads(p.read_text())
            self.assertEqual(s["permissions"], {"allow": ["Bash(ls)"]})
            self.assertEqual(s["enabledMcpjsonServers"], ["a", "b"])
            self.assertEqual(s["enabledPlugins"], {"p@x": True})
            self.assertEqual(s["hooks"]["SessionStart"][0]["hooks"][0]["command"], "bd prime --hook-json")

    def test_merge_creates_file(self):
        with tempfile.TemporaryDirectory() as d:
            p = Path(d) / ".claude" / "settings.json"
            r.merge_settings(p, [], [])
            self.assertEqual(json.loads(p.read_text())["enabledMcpjsonServers"], [])


class EnvRefs(unittest.TestCase):
    def test_collects(self):
        self.assertEqual(r.env_refs({**STDIO, **FWD, **HTTP}),
                         {"DATABASE_URL": True, "GITHUB_PERSONAL_ACCESS_TOKEN": False, "API_TOKEN": False})


if __name__ == "__main__":
    unittest.main()
