#!/usr/bin/env python3
"""Render harness configs from a repo's .mcp.json (+ optional overlay). Stdlib only.

usage: render.py render DIR [--overlay overlay.json]
       render.py envcheck DIR
"""
import json
import os
import re
import shutil
import sys
from pathlib import Path

HEADER = "generated by agent-baseline - edit .mcp.json instead"
ENV_RE = re.compile(r"^\$\{([A-Za-z_][A-Za-z0-9_]*)(?::-(.*))?\}$")
ANY_ENV_RE = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)(?::-([^}]*))?\}")
BEARER_RE = re.compile(r"^Bearer \$\{([A-Za-z_][A-Za-z0-9_]*)\}$")
BARE_KEY = re.compile(r"^[A-Za-z0-9_-]+$")


class RenderError(Exception):
    pass


def env_ref(v):
    """(var, default_or_None) when v is exactly '${VAR}' or '${VAR:-d}', else None."""
    m = ENV_RE.match(v) if isinstance(v, str) else None
    return (m.group(1), m.group(2)) if m else None


def tstr(s):
    return json.dumps(s)  # JSON string escaping is valid TOML basic-string escaping


def tkey(k):
    return k if BARE_KEY.match(k) else tstr(k)


def render_codex(mcp):
    out = [f"# {HEADER}", ""]
    for name, s in mcp.items():
        t = s.get("type", "stdio")
        out.append(f"[mcp_servers.{tkey(name)}]")
        if t == "stdio":
            out.append(f"command = {tstr(s['command'])}")
            if s.get("args"):
                out.append("args = [" + ", ".join(tstr(a) for a in s["args"]) + "]")
            fwd, lit = [], {}
            for k, v in (s.get("env") or {}).items():
                ref = env_ref(v)
                if ref is None:
                    lit[k] = v
                    continue
                var, default = ref
                if var == k:
                    fwd.append(var)
                    if default is not None:
                        lit[k] = default
                elif default is not None:
                    lit[k] = default  # Codex cannot remap a variable; the default is what it gets
                else:
                    raise RenderError(f"{name}: env {k}=${{{var}}} - Codex forwards a variable only under its own name; add a :-default or rename")
            if fwd:
                out.append("env_vars = [" + ", ".join(tstr(v) for v in fwd) + "]")
            if lit:
                out.append(f"[mcp_servers.{tkey(name)}.env]")
                out.extend(f"{tkey(k)} = {tstr(v)}" for k, v in lit.items())
        elif t in ("http", "sse"):
            out.append(f"url = {tstr(s['url'])}")
            for h, v in (s.get("headers") or {}).items():
                m = BEARER_RE.match(v) if h == "Authorization" else None
                if not m:
                    raise RenderError(f"{name}: header {h!r} - Codex supports only 'Authorization: Bearer ${{VAR}}'")
                out.append(f"bearer_token_env_var = {tstr(m.group(1))}")
        else:
            raise RenderError(f"{name}: unknown type {t!r}")
        out.append("")
    out += ["[features]", "hooks = true", ""]
    return "\n".join(out)


def oc_env(v):
    return ANY_ENV_RE.sub(r"{env:\1}", v)


def render_opencode(mcp):
    servers = {}
    for name, s in mcp.items():
        t = s.get("type", "stdio")
        if t == "stdio":
            e = {"type": "local", "command": [s["command"], *s.get("args", [])], "enabled": True}
            if s.get("env"):
                e["environment"] = {k: oc_env(v) for k, v in s["env"].items()}
        elif t in ("http", "sse"):
            e = {"type": "remote", "url": s["url"], "enabled": True}
            if s.get("headers"):
                e["headers"] = {k: oc_env(v) for k, v in s["headers"].items()}
        else:
            raise RenderError(f"{name}: unknown type {t!r}")
        servers[name] = e
    return json.dumps({"$schema": "https://opencode.ai/config.json", "mcp": servers}, indent=2) + "\n"


def merge_settings(path, mcp_names, plugins):
    d = json.loads(path.read_text()) if path.exists() else {}
    d.setdefault("hooks", {})["SessionStart"] = [
        {"matcher": "", "hooks": [{"type": "command", "command": "bd gate check >/dev/null 2>&1; bd prime --hook-json"}]}
    ]
    d["enabledMcpjsonServers"] = sorted(mcp_names)
    d["enabledPlugins"] = {**d.get("enabledPlugins", {}), **{p: True for p in plugins}}  # add, never drop
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(d, indent=2, sort_keys=True) + "\n")


def render_agents(src, targets):
    files = [p for p in src.glob("*.md") if p.name != "README.md"] if src.is_dir() else []
    for t in targets:
        if files:
            t.mkdir(parents=True, exist_ok=True)
        for p in files:
            shutil.copyfile(p, t / p.name)  # per-harness model mapping lands with the model-routing baseline


def env_refs(mcp):
    """{VAR: has_default} over every env value and header in .mcp.json."""
    refs = {}
    for s in mcp.values():
        for v in list((s.get("env") or {}).values()) + list((s.get("headers") or {}).values()):
            for var, default in ANY_ENV_RE.findall(v):
                refs[var] = refs.get(var, False) or default != ""
    return refs


def envcheck(mcp):
    missing = 0
    for var, has_default in sorted(env_refs(mcp).items()):
        if os.environ.get(var):
            print(f"  ✓ {var}")
        elif has_default:
            print(f"  · {var}  (unset; Claude and Codex use the default, OpenCode has none)")
        else:
            print(f"  ✗ {var}  - export it in your shell (nix: secrets/mcp.yaml -> .zshrc.mcp-secrets)")
            missing += 1
    return missing


def load_mcp(d):
    p = d / ".mcp.json"
    return json.loads(p.read_text())["mcpServers"] if p.exists() else {}


def main(argv):
    if len(argv) < 2 or argv[0] not in ("render", "envcheck"):
        sys.exit(__doc__)
    cmd, d = argv[0], Path(argv[1])
    mcp = load_mcp(d)
    if cmd == "envcheck":
        sys.exit(1 if envcheck(mcp) else 0)
    overlay = json.loads(Path(argv[argv.index("--overlay") + 1]).read_text()) if "--overlay" in argv else {}
    (d / ".codex").mkdir(exist_ok=True)
    (d / ".codex" / "config.toml").write_text(render_codex(mcp))
    (d / "opencode.json").write_text(render_opencode(mcp))
    merge_settings(d / ".claude" / "settings.json", mcp.keys(), overlay.get("plugins", []))
    render_agents(d / "agents", [d / ".claude" / "agents", d / ".opencode" / "agents"])


if __name__ == "__main__":
    try:
        main(sys.argv[1:])
    except RenderError as e:
        sys.exit(f"render.py: {e}")
